### ISSUE TITLE
Timestamp wrong

### ISSUE THREAD

**Issue by tungmeister** [bimmerconnected/ha_custom_component#1]
Hi, I've tested today. There's no errors and the messages get delivered however the time shown is an hour behind and there's no actual notification of the message having arrived on the idrive (though this might be because it thinks it's an hour old?)

**Comment by gerard33** [comment]
Thanks for testing. In the meanwhile we have released a new version where the notify service must be used for message and POI.
So there are no `bmw_connected_drive.send_message` and `bmw_connected_drive.send_poi` anymore. See the readme file for extra info.

We are not finished yet, but maybe you can already test this?

And the timestamp shown is not from when the message is sent, but when the message is received in the car. I do see new messages have arrived, see the first picture in the readme file for the envelope with a 7.

cc @rikroe

**Comment by tungmeister** [comment]
I'll test again in an hour or so. No I didn't get the message indicator or message count, I could only see that I'd got a message after going into connected drive messages.

**Comment by gerard33** [comment]
I just did some tests an hour ago and didn't get that screen as well, though no messages either. So maybe something wrong with the BMW services or something with the latest version :see_no_evil:

But with the version you used for testing earlier, I did get the screen as shown on the photo.

**Comment by tungmeister** [comment]
Just tested again. The message was delivered but there was no notification. The time is definitely showing 1 hour behind still which is strange if that stamp is only generated when the message is received. 
![IMG_20200331_213404](https://user-images.githubusercontent.com/127809/78072897-c4f70380-7397-11ea-8d23-f6d4c2a8466f.jpg)

**Comment by gerard33** [comment]
In which timezone are you? Maybe an UTC difference?

**Comment by tungmeister** [comment]
I'm in the UK so UTC + 1 which is maybe causing it, though that would be a strange limitation on BMWs part.

**Comment by gerard33** [comment]
As you can see in my photos in the readme file, the times on the display and for the message are the same (1 minute difference). And I am in The Netherlands, so UTC-2 with the summer time now. So that's not causing the issue I guess.

**Comment by tungmeister** [comment]
It will be a non issue if noficatons are shown on the main screen, I'm just hoping it's just one of the many issues that the BMW servers have. I'll have another play tomorrow and test if a notification appears when I send a POI from the connected drive app.

**Comment by gerard33** [comment]
Yeah, notifications should appear indeed. And also good to see which time is shown when you send a POI from the app.

**Comment by rikroe** [comment]
@tungmeister if you're trying tomorrow, please refresh the component. I've pushed some changes (multiple accounts/vehicles supported, POI attributes for display in the car)

**Comment by tungmeister** [comment]
@rikroe yeah I'll update the component before testing. I might do it later on tonight depending on how much wine I drink!

**Comment by gerard33** [comment]
And some more minor changes to the component -> https://github.com/bimmerconnected/ha_custom_component/commit/5e8dd32b7d3586dc1ffd0ca6684216b7c8496bbe

Please use this version for further testing.

**Comment by gerard33** [comment]
Messages have arrived in my car, also visible as new messages.

Timestamps are the times on which they arrive in my car, so no time differences.

**Comment by tungmeister** [comment]
Just to update you, I've tested again this evening and I still don't get notified of the message and the time stamp is still an hour out. I experienced the same issues with a POI sent from the app so I'm guessing it's something on my idrive that's causing it. I'll check coding tomorrow and report back.

**Comment by gerard33** [comment]
Thanks for the update. We have released an update of the library v0.7.5 and some minor updates to `notify.py`. The latest versions of the files are in this repo.
Please use this version for further testing.

Good to see the app gives you the same issues, then we know the bimmer_connected library works as expected.

I did some more tests with the latest version with my car and I receive the messages and POIs as earlier, so available in the notification overview and with the time they arrived in the car.
In the meanwhile we have made a PR for HA.

**Comment by gerard33** [comment]
The PR with the notify service is available in HA 0.109.
Thanks for the testing.
